config/routes.rb
Sample::Application.routes.draw do
  devise_for :users

   resources :albums do
  member do
      post 'tag'
end
end

   root :to => 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :description, :name, :artist,:avatar,:images,:images_attributes,:user_id,:tag_name
belongs_to :user
has_many :images , :dependent => :destroy
accepts_nested_attributes_for :images, :reject_if =>  :all_blank
end

app/models/image.rb
class Image < ActiveRecord::Base 
	attr_accessible :avatar,:tag_name
	belongs_to :album
	mount_uploader :avatar, AvatarUploader 
	
end

app/models/user.rb
class User < ActiveRecord::Base
  
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable
	has_many :albums
attr_accessible :email, :password, :password_confirmation,:remember_me,:firstname,:lastname, :age,:gender,:dateofbirth,:phone,:address
	
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_filter :authenticate_user!

	def index
    @user=current_user
		@album=@user.albums
	end

	def new
		@album=Album.new
		2.times do
			@album.images.build 
		end
  end
	def create
    @user=current_user
		@album=@user.albums.new(params[:album])
			if @album.save
				redirect_to album_path(@album)
			else
				render :action=>'new'
			end
	end 

	def show
		@album=Album.find(params[:id])            
	end

	def edit
		@album=Album.find(params[:id])
	end

	def destroy
		@album=Album.find(params[:id])
		@album.destroy
    redirect_to albums_path
	end

	def update
		@album=Album.find(params[:id])
		@album.update_attributes(params[:album])
    redirect_to albums_path
	end
        
               
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/albums_helper.rb
module AlbumsHelper
	def link_to_remove_fields(name, f)
		f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
	end

	def link_to_add_fields(name, f, association)
		new_object = f.object.class.reflect_on_association(association).klass.new
		fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
		render(association.to_s.singularize + "_fields", :f => builder)
		end
		link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<html>
<div class="form">
	<%= form_for @album,:url=>albums_path do |f| %>
		<%= f.error_messages %> 

			<div class="field">
				<%= f.label :Album_name %><br />
				<%= f.text_field :name %>
			</div>

			<div class="field">
				<%= f.label :Artist %><br />
				<%= f.text_field :artist %>
			</div>

                        <div class="field">
				<%= f.label :description %><br />
				<%= f.text_area :description %>
			</div>
			<div class="img">
				<%= f.fields_for :images do |builder|%>
				<%= render "image_fields", :f => builder %>
        <% end %>
			</div>
				
			<p><%= link_to_add_fields "Add images", f,:images %></p><br/>
			
 <%#= f.hidden_field :user_id, :value => current_user.id %>
	<div class="actions">
	<%= f.submit %>
	</div>
	<% end %>
</div>
</html>

app/views/albums/_image_fields.html.erb
<html>
<div class="fields">
 Image: <br/><%= f.file_field :avatar %><br/>
tag name:<%= f.text_field :tag_name %>(use comma for multiple tags)
 <%= link_to_remove_fields "remove", f %>
  
</div>
</html>

app/views/albums/edit.html.erb
<html>
<div class="form">
	<%= form_for @album,:url=>album_path do |f| %>
		<%= f.error_messages %> 

			<div class="field">
				<%= f.label :Album_name %><br />
				<%= f.text_field :name %>
			</div>

			<div class="field">
				<%= f.label :Artist %><br />
				<%= f.text_field :artist %>
			</div>

                        <div class="field">
				<%= f.label :description %><br />
				<%= f.text_area :description %>
			</div>
			<div class="img">
				<%= f.fields_for :images do |builder|%>
				<%= render "image_fields", :f => builder %>
        <% end %>
			</div>
				
			<p><%= link_to_add_fields "Add images", f,:images %></p><br/>
			
 <%= f.hidden_field :user_id, :value => current_user.id %>
	<div class="actions">
	<%= f.submit %>
	</div>
	<% end %>
</div>
<%=  link_to "back",albums_path %>
</html>

app/views/albums/index.html.erb
<html>

<h1>Listing all albums</h1>

<table>
  <tr>
    <th>Album_Name</th>
    <th>Artist</th>
    <th>Album_Desc</th>
     
    <th></th>
    <th></th>
  </tr>

<% @album.each do |album| %>
  <tr>
    <td><%= album.name %></td>
    <td><%= album.artist %></td>
    <td><%= album.description %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New album', new_album_path %>

</html>

app/views/albums/new.html.erb
	<h1>New game</h1>

	<%= render 'form' %>

	<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<center>
<p>
  <b>Name:</b>
  <%= @album.name %>
</p>

<p>
  <b>Artist:</b>
  <%= @album.artist %>
</p>

<p>
  <b>Description:</b>
  <%= @album.description %>
</p></center>
<ul>
<% for album in @album.images %>
<li>

<%= image_tag album.avatar.url,:size => "100x100"  %></br>
Tag Names:
  <% album.tag_name.split( /, */).each do |i| %>

<%= i %>
<% end %>

</li>
<% end %>

</ul>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body bgcolor='#b0c4de'>


<% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
      
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>

<%= yield %>

</body>
</html>